name: Dump Supabase

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get install -y postgresql-client

      - name: Dump database
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pg_dump --clean --if-exists \
            --quote-all-identifiers \
            --no-owner --no-privileges \
            --schema=kubi --schema=sahut \
            -h aws-1-ap-southeast-1.pooler.supabase.com \
            -p 5432 \
            -U postgres.edxwafkjordqqfqpptwv \
            -d postgres \
            -f dump.sql

      - name: Upload dump
        uses: actions/upload-artifact@v4
        with:
          name: supabase-dump
          path: dump.sql
